### ISSUE TITLE
Last entry in web "News" section says 09/feb/2022 where it should be 09/02/2023

### ISSUE THREAD

**Issue by datalot-369** [imvenx/cssvg#38]
![image](https://github.com/imvenx/cssvg/assets/21994415/4777fe96-7a40-419e-881a-340fb4834f3d)

**Comment by imvenx** [comment]
Fixed, thanks for reporting! The right repo to report web issues would be https://github.com/imvenx/cssvgweb :)

**Comment by imvenx** [comment]
Fixed, thanks for reporting! The right repo to report web issues would be https://github.com/imvenx/cssvgweb :)
