### ISSUE TITLE
404 at https://imvenx.github.io/cssvgweb/#/

### ISSUE THREAD

**Issue by pdurbin** [imvenx/cssvg#45]
Hi! I heard about this project during the Inkscape 20th anniversary yesterday.

I clicked https://imvenx.github.io/cssvgweb/#/ in the README but it's a 404.

It there a new URL we should visit?

Thank you.

**Comment by imvenx** [comment]
> Hi! I heard about this project during the Inkscape 20th anniversary yesterday.
> 
> I clicked https://imvenx.github.io/cssvgweb/#/ in the README but it's a 404.
> 
> It there a new URL we should visit?
> 
> Thank you.

Hi! Yes now is https://imvenx.github.io/inkaweb/#/

Can you tell me where did you get the old link so I fix it? Thanks!

**Comment by imvenx** [comment]
Anyways the web is outdated latest build is here https://github.com/imvenx/inka/releases/tag/v1.3.2

**Comment by imvenx** [comment]
anyways 2 I updated it so now it points to latest releases :)

**Comment by pdurbin** [comment]
Thanks! Yes, it looks like the link was fixed in the README in c9bf90a.

The old link still appears in the top right:

<img width="759" alt="Screenshot 2023-11-19 at 12 30 46 PM" src="https://github.com/imvenx/inka/assets/21006/cbd47adf-63a2-412d-aa14-f8afe44fd077">

**Comment by imvenx** [comment]
> Thanks! Yes, it looks like the link was fixed in the README in [c9bf90a](https://github.com/imvenx/inka/commit/c9bf90a3e92284e54ec178ba104cc6a952125177).
> 
> The old link still appears in the top right:
> <img alt="Screenshot 2023-11-19 at 12 30 46 PM" width="759" src="https://user-images.githubusercontent.com/21006/284078531-cbd47adf-63a2-412d-aa14-f8afe44fd077.png">

fixed! Thanks!

**Comment by pdurbin** [comment]
Much better. Thanks!
